import os
import re
from langgraph.graph import StateGraph, END
from state import AgentState
from llm_factory import get_llm
from langchain_core.messages import SystemMessage, HumanMessage

# Define the Nodes (Agentic Steps)
def planner_node(state: AgentState):
    """
    Uses the LLM to analyze the user request and generate a step-by-step plan.
    """
    print("\n[Node: Planner] LLM is analyzing the request...")
    
    llm = get_llm()
    
    # Properly format the prompt using Chat Messages
    messages = [
        SystemMessage(content="You are a senior software architect working on a C# .NET 8 Minimal API URL Shortener."),
        HumanMessage(content=f"""The user has requested the following feature:
"{state['user_request']}"

Create a concise, 3-step execution plan to implement this feature. 
Return ONLY the numbered steps as a plain text list, with no intro or outro text.""")
    ]
    
    # Invoke with the message list
    response = llm.invoke(messages)
    raw_content = extract_text_from_content(response.content)
    plan_steps = [step.strip() for step in raw_content.split('\n') if step.strip()]
    
    # Clean up the response
    plan_steps = [step.strip() for step in raw_content.split('\n') if step.strip()]
    
    print("Plan generated by AI \n")
    for step in plan_steps:
        print(f"    {step}")
        
    return {"plan": plan_steps}

def coder_node(state: AgentState):
    """
    Reads the plan and existing codebase, prompts the LLM to generate the updated C# code,
    streams the output to the console in real-time, and updates state['generated_code'].
    """
    print("\n" + "="*50)
    print("[Node: Coder] Synthesizing C# code from plan...")
    print("="*50 + "\n")

    # Locate and read the existing Program.cs file for context
    target_path = "src/UrlShortener/Program.cs"
    if not os.path.exists(target_path):
        for root, _, files in os.walk("src"):
            if "Program.cs" in files:
                target_path = os.path.join(root, "Program.cs")
                break

    existing_code = ""
    if os.path.exists(target_path):
        with open(target_path, "r", encoding="utf-8") as f:
            existing_code = f.read()

    # Format the execution plan from state
    plan_text = "\n".join(state.get("plan", []))

    #  Construct the prompt securely without parsing confusion
    human_prompt = (
        f"User Request:\n{state['user_request']}\n\n"
        f"Execution Plan:\n{plan_text}\n\n"
        f"Current Program.cs:\n```csharp\n{existing_code}\n```\n\n"
        "Implement the requested changes into Program.cs. Ensure all existing routes, database contexts, and models remain functional alongside the new alias logic."
    )

    messages = [
        SystemMessage(content=(
            "You are a principal C# .NET 8 developer. Write clean, idiomatic Minimal API code. "
            "Return ONLY the complete updated C# file contents enclosed in a single ```csharp markdown code fence. "
            "Do not include conversational greetings, explanations, or notes outside the code fence."
        )),
        HumanMessage(content=human_prompt)
    ]

    # Stream response
    llm = get_llm()
    full_response = ""

    for chunk in llm.stream(messages):
        text_piece = extract_text_from_content(chunk.content)
        print(text_piece, end="", flush=True)
        full_response += text_piece

    print("\n\n" + "-"*50)
    print(" -> Code generation complete.")
    print("-"*50)

    # 5. Extract raw code from markdown fences
    code_match = re.search(r"```(?:csharp)?\s*(.*?)\s*```", full_response, re.DOTALL)
    extracted_code = code_match.group(1) if code_match else full_response.strip()

    return {
        "generated_code": {target_path: extracted_code}
    }


def disk_writer_node(state: AgentState):
    """
    Takes the AI generated code from in memory and writes it to the physical file system
    so the validator can compile and run tests against it.
    """
    print("\n[Node: Disk Writer] Writing generated code to disk...")
    
    generated_code = state.get("generated_code", {})
    
    if not generated_code:
        print(" -> No code found in state to write.")
        return {}
        
    for file_path, code_content in generated_code.items():
        # Ensure the target directory exists before writing
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        # Write the new code to the file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code_content)
            
        print(f" -> Successfully updated: {file_path}")
        
    return {}

def validator_node(state: AgentState):
    """
    Executes the .NET test suite against the generated code.
    Simulates a failure on the first attempt and success on subsequent attempts.
    Updates test results and increments the retry counter.
    """
    print("\n[Node: Validator] Running 'dotnet test' against the codebase...")
    
    current_retries = state.get("retry_count", 0)
    passed = current_retries > 0 
    
    if passed:
        print(" -> Output: Tests Passed!")
    else:
        print(" -> Output: Tests Failed! (Simulated)")
        
    return {
        "test_results": {"passed": passed}, 
        "retry_count": current_retries + 1
    }

def human_gate_node(state: AgentState):
    """
    Acts as an approval checkpoint before code is considered finalized.
    """
    print("\n[Node: Human Gate] Feature ready. Pausing for human review...")
    return {}

# Conditional Logic

def route_after_validation(state: AgentState):
    """
    Evaluates the test results to determine the next node.
    Routes to the human gate if tests pass, loops back to the coder if they fail,
    or terminates the graph if the maximum retry limit is reached.
    """
    passed = state.get("test_results", {}).get("passed", False)
    retries = state.get("retry_count", 0)
    
    if passed:
        return "human_gate"
    elif retries < 3:
        print(f" -> Retrying... (Attempt {retries} of 3)")
        return "coder"
    else:
        print(" -> Max retries reached. Triggering rollback/abort.")
        return END

# Build Graph

workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("planner", planner_node)
workflow.add_node("coder", coder_node)
workflow.add_node("disk_writer", disk_writer_node)
workflow.add_node("validator", validator_node)
workflow.add_node("human_gate", human_gate_node)

# set start
workflow.set_entry_point("planner")

# Connect nodes
workflow.add_edge("planner", "coder")
workflow.add_edge("coder", "disk_writer")
workflow.add_edge("disk_writer", "validator")

# Add conditional edge
workflow.add_conditional_edges(
    "validator",
    route_after_validation,
    {
        "human_gate": "human_gate",
        "coder": "coder",
        END: END
    }
)

# Set End, End human review
workflow.add_edge("human_gate", END)

# Compile
app = workflow.compile()

# Helper function to extract text content
def extract_text_from_content(content) -> str:
    """
    Safely extracts plain text whether the LLM returns a string 
    or a list of multimodal/structured blocks.
    """
    if isinstance(content, list):
        return "".join([
            b.get("text", "") if isinstance(b, dict) else str(b) 
            for b in content
        ])
    return str(content)