import os
import re
from langgraph.graph import StateGraph, END
from state import AgentState
from llm_factory import get_llm
from langchain_core.messages import SystemMessage, HumanMessage
import subprocess
import time
from langchain_google_genai.chat_models import GoogleRateLimitError

# Define the Nodes (Agentic Steps)
def planner_node(state: AgentState):
    """
    Uses the LLM to analyze the user request and generate a step-by-step plan.
    """
    print("\n[Node: Planner] LLM is analyzing the request...")
    
    messages = [
        SystemMessage(content="You are a senior software architect working on a C# .NET 10 Minimal API URL Shortener."),
        HumanMessage(content=f"""The user has requested the following feature:
"{state['user_request']}"

Create a concise, 3-step execution plan to implement this feature. 
Return ONLY the numbered steps as a plain text list, with no intro or outro text.""")
    ]
    
    # Call the LLM with auto-pause protection
    llm = get_llm()
    max_api_retries = 3
    for attempt in range(max_api_retries):
        try:
            response = llm.invoke(messages)
            break
        except GoogleRateLimitError:
            print(f"\n[API LIMIT TRIGGERED in Planner] Auto-pausing for 65 seconds...")
            time.sleep(65)
            
    # Extract and clean up the response
    raw_content = extract_text_from_content(response.content)
    plan_steps = [step.strip() for step in raw_content.split('\n') if step.strip()]
    
    print("Plan generated by AI \n")
    for step in plan_steps:
        print(f"    {step}")
        
    return {"plan": plan_steps}

def coder_node(state: AgentState):
    """
    Reads the plan and entire existing codebase, prompts the LLM to generate the updated C# code
    for specific files, streams the output to the console, and updates state['generated_code'].
    """
    print("\n" + "="*50)
    print("[Node: Coder] Synthesizing C# .NET 10 code from plan...")
    print("="*50 + "\n")

    #  Read the entire C# codebase for context
    # False for fast targeted testing
    FULL_WORKSPACE_SCAN = False 
    
    existing_codebase = ""

    if FULL_WORKSPACE_SCAN:
        print(" -> [Config] Scanning entire src/ directory for context...")
        for root, dirs, files in os.walk("src/UrlShortener"):
            if "bin" in root or "obj" in root: 
                continue
            for file in files:
                if file.endswith(".cs"):
                    path = os.path.join(root, file).replace("\\", "/")
                    with open(path, "r", encoding="utf-8") as f:
                        existing_codebase += f"\n### File: {path}\n```csharp\n{f.read()}\n```\n"
    else:
        print(" -> [Config] Fast mode enabled. Scanning targeted files only...")
        target_files = [
            "src/UrlShortener/Program.cs",
            # "src/UrlShortener/Endpoints/UrlEndpoints.cs",
            # "src/UrlShortener/Data/AppDbContext.cs",
        ]
        for path in target_files:
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    existing_codebase += f"\n### File: {path}\n```csharp\n{f.read()}\n```\n"
            else:
                print(f" -> Warning: Could not find {path}")

    # 2. Format the execution plan from state
    plan_text = "\n".join(state.get("plan", []))

    # 3. Check for previous compiler errors
    test_results = state.get("test_results", {})
    build_errors = test_results.get("output", "")
    
    error_context = ""
    if build_errors:
        error_context = (
            f"\n\n⚠️ PREVIOUS BUILD FAILED ⚠️\n"
            f"Here are the compiler errors from your last attempt:\n"
            f"```text\n{build_errors}\n```\n"
            f"Please fix these specific errors in your new code."
        )

    # 4. Construct the prompt securely
    human_prompt = (
        f"User Request:\n{state['user_request']}\n\n"
        f"Execution Plan:\n{plan_text}\n\n"
        f"Current Codebase:\n{existing_codebase}\n"
        f"{error_context}\n\n"
        "Implement the requested changes. Modify ONLY the files that need updating (e.g., src/UrlShortener/Data/AppDbContext.cs, src/UrlShortener/Endpoints/UrlEndpoints.cs, etc.). "
        "IMPORTANT: Do NOT redefine existing classes if they already exist in their own files. Respect the existing project structure."
    )

    messages = [
        SystemMessage(content=(
            "You are a principal C# .NET 10 developer. Write clean, idiomatic Minimal API code. "
            "For EACH file you modify, you MUST output it using exactly this format:\n"
            "### File: src/UrlShortener/path/to/file.cs\n"
            "```csharp\n"
            "// complete updated file code here\n"
            "```\n"
            "CRITICAL REQUIREMENT: You are modifying an existing codebase. You MUST output the ENTIRE, fully updated file from top to bottom. "
            "NEVER use placeholders like '// ... existing code ...' or '// previous endpoints'. "
            "You must retain all existing imports, database models, and previous endpoints. If you omit any existing code, the application will break. "
            "Do not include conversational text outside the code blocks."
        )),
        HumanMessage(content=human_prompt)
    ]

    # 5. Stream response tokens in real-time to the terminal
    llm = get_llm()
    full_response = ""
    
    max_api_retries = 3
    for attempt in range(max_api_retries):
        try:
            for chunk in llm.stream(messages):
                # Use our helper function to extract text cleanly
                text_piece = extract_text_from_content(chunk.content)
                
                print(text_piece, end="", flush=True)
                full_response += text_piece
                
            break  # If successful, break out of the retry loop!
            
        except GoogleRateLimitError:
            print(f"\n\n[API LIMIT TRIGGERED] The free tier is exhausted.")
            print(f" -> Auto-pausing for 65 seconds before retry {attempt + 1} of {max_api_retries}...")
            time.sleep(65)  # Wait slightly longer than the 60s Google limit
            print("\n[Resuming Code Generation...]\n")
            full_response = "" # Reset the response string for the fresh attempt
    

    print("\n\n" + "-"*50)
    print(" -> Code generation complete.")
    print("-"*50)

    # 6. Extract raw code for multiple files
    file_updates = {}
    
    # Regex to find "### File: path/to/file.cs" followed by a csharp code block
    pattern = r"### File:\s*(src/.*?\.cs)\s*```(?:csharp)?\s*(.*?)\s*```"
    
    for match in re.finditer(pattern, full_response, re.DOTALL):
        file_path = match.group(1).strip()
        code = match.group(2).strip()
        file_updates[file_path] = code

    # Fallback just in case the LLM outputs code without a file path header
    if not file_updates:
        code_match = re.search(r"```(?:csharp)?\s*(.*?)\s*```", full_response, re.DOTALL)
        if code_match:
            print(" -> Warning: File path header missing. Defaulting to Program.cs")
            file_updates["src/UrlShortener/Program.cs"] = code_match.group(1).strip()

    return {
        "generated_code": file_updates
    }

def disk_writer_node(state: AgentState):
    """
    Takes the AI generated code from in memory and writes it to the physical file system
    so the validator can compile and run tests against it.
    """
    print("\n[Node: Disk Writer] Writing generated code to disk...")
    
    generated_code = state.get("generated_code", {})
    
    if not generated_code:
        print(" -> No code found in state to write.")
        return {}
        
    for file_path, code_content in generated_code.items():
        # Ensure the target directory exists before writing
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        # Write the new code to the file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code_content)
            
        print(f" -> Successfully updated: {file_path}")
        
    return {}

def validator_node(state: AgentState):
    """
    Executes the real .NET compiler against the generated code.
    Captures the output to determine if the build succeeded.
    """
    print("\n[Node: Validator] Running real 'dotnet build' against the codebase...")
    
    # Define the path to your .NET project
    # (Adjust this if your .csproj is located in a different folder)
    project_path = "src/UrlShortener"
    
    try:
        # Run the dotnet build command in the terminal
        result = subprocess.run(
            ["dotnet", "build", project_path],
            capture_output=True,
            text=True,
            check=False # We don't want Python to crash on a build error; we want to catch it!
        )
        
        # returncode 0 means the build was successful
        passed = (result.returncode == 0)
        
        if passed:
            print(" -> Output: Build Passed Successfully! ✅")
            compiler_output = "Build succeeded."
        else:
            print(" -> Output: Build Failed! ❌")
            print(" -> Capturing errors for the next attempt...")
            # Grab the actual error so we can feed it back to the AI
            compiler_output = result.stdout + "\n" + result.stderr
            
    except Exception as e:
        passed = False
        compiler_output = f"Failed to execute dotnet command: {str(e)}"
        print(f" -> Execution Error: {compiler_output}")
        
    current_retries = state.get("retry_count", 0)
    
    return {
        "test_results": {
            "passed": passed,
            "output": compiler_output  # Saving the real error to state
        }, 
        "retry_count": current_retries + 1
    }

def human_gate_node(state):
    """
    Acts as an approval checkpoint. Prompts the user via CLI to approve or reject.
    Includes input validation to prevent typos from triggering unwanted loops.
    """
    print("\n" + "="*50)
    print("[Node: Human Gate] Code compiled successfully!")
    print("="*50 + "\n")
    
    print("Please review the generated code or test the local endpoints.")
    
    # 1. Enforce strict 'y' or 'n' input
    while True:
        choice = input("Approve these changes? (y/n): ").strip().lower()
        if choice in ['y', 'yes', 'n', 'no']:
            break
        print(" -> Invalid input. Please type 'y' or 'n'.")
        
    if choice in ['y', 'yes']:
        print(" -> Changes approved! Finalizing workflow.")
        return {"human_approved": True}
    else:
        # 2. Enforce that feedback cannot be empty
        while True:
            feedback = input("\n[Feedback] What needs to be changed or fixed? \n> ").strip()
            if feedback:
                break
            print(" -> Feedback cannot be empty. Please tell the AI what to fix.")
            
        print(" -> Feedback received. Routing back to the AI...")
        
        updated_request = state['user_request'] + f"\n\nHUMAN FEEDBACK ON PREVIOUS ATTEMPT:\n{feedback}"
        
        return {
            "human_approved": False,
            "user_request": updated_request,
            "retry_count": 0,
            "test_results": {}
        }

def doc_generator_node(state):
    """
    Parallel, Generates Markdown API documentation based on the plan.
    """
    print("\n[Node: Doc Generator] Generating API documentation in parallel...")
    
    plan_text = "\n".join(state.get("plan", []))
    
    # Simple prompt asking the LLM to write documentation
    prompt = f"""
    Based on the following feature plan, write a brief API documentation in Markdown format.
    Include endpoint routes, methods, and expected payloads.
    Do NOT write code, only Markdown documentation.
    
    Plan:
    {plan_text}
    """
    
    # calling llm
    llm = get_llm()
    response = llm.invoke(prompt)
    docs_content = response.content
    
    # For now, we will simulate the LLM output to test the graph structure
    docs_content = f"# API Documentation\n\nUpdated based on plan:\n{plan_text}"
    
    # Save it directly to disk
    with open("src/UrlShortener/API_DOCS.md", "w") as f:
        f.write(docs_content)
        
    print(" -> Successfully saved: src/UrlShortener/API_DOCS.md")
    return {}

# Conditional Logic

def route_after_validation(state: AgentState):
    """
    Evaluates the test results to determine the next node.
    Routes to the human gate if tests pass, loops back to the coder if they fail,
    or terminates the graph if the maximum retry limit is reached.
    """
    passed = state.get("test_results", {}).get("passed", False)
    retries = state.get("retry_count", 0)
    
    if passed:
        return "human_gate"
    elif retries < 3:
        print(f" -> Retrying... (Attempt {retries} of 3)")
        print(" -> Pausing for 20 seconds to respect free API rate limits...")
        time.sleep(20)
        return "coder"
    else:
        print(" -> Max retries reached. Triggering rollback/abort.")
        return END

def route_after_human(state):
    """Routes to END if approved, or loops back to Planner if rejected."""
    if state.get("human_approved", True):
        return END
    else:
        return "planner"


# Build Graph

workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("planner", planner_node)
workflow.add_node("coder", coder_node)
workflow.add_node("disk_writer", disk_writer_node)
workflow.add_node("doc_generator", doc_generator_node)
workflow.add_node("validator", validator_node)
workflow.add_node("human_gate", human_gate_node)

# set start
workflow.set_entry_point("planner")

# Connect nodes
workflow.add_edge("planner", "coder")
workflow.add_edge("planner", "doc_generator")
workflow.add_edge("coder", "disk_writer")
workflow.add_edge("disk_writer", "validator")
workflow.add_edge("doc_generator", "validator")


# Add conditional edge
workflow.add_conditional_edges(
    "validator",
    route_after_validation,
    {
        "human_gate": "human_gate",
        "coder": "coder",
        END: END
    }
)

workflow.add_conditional_edges(
    "human_gate",
    route_after_human,
    {
        END: END,
        "planner": "planner"
    }
)

# Set End, End human review
workflow.add_edge("human_gate", END)

# Compile
app = workflow.compile()

# Helper function to extract text content
def extract_text_from_content(content) -> str:
    """
    Safely extracts plain text whether the LLM returns a string 
    or a list of multimodal/structured blocks.
    """
    if isinstance(content, list):
        return "".join([
            b.get("text", "") if isinstance(b, dict) else str(b) 
            for b in content
        ])
    return str(content)